name: NPM Publish
on:
  release:
    types: [created]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'
          cache: 'npm'
          scope: '@snoconedev'
        - name: NPM install and build
          run: npm install && npm run build
        - name: NPM Version based on release tag
          run: npm version ${{ github.event.release.tag_name }} --allow-same-version --no-git-tag-version
        - name: NPM publish
          run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}